### PR TITLE
Create specs for the following actions creators

### PR DESCRIPTION
**Pull request by walkerrandolphsmith**
- resetDetails
- closeDetails
- openDetails

### CODE REVIEW

**Comment by walkerrandolphsmith** [comment]
I believe this was done in another pr! :/

**Comment by vutran** [comment]
Thanks for the PR. This has been done in #82. Will try to get some more issues up for #hacktoberfest. 👍

**Comment by walkerrandolphsmith** [comment]
Awesome project. I currently use alfred. I have also created two alfred plugins. 
https://github.com/walkerrandolphsmith/VersionOne.alfred.workflow
https://github.com/walkerrandolphsmith/Continuum.alfred.workflow

I would love to get them ported to JavaScript and on dext. Can you point me in the right direction?

**Comment by vutran** [comment]
Sure. Join the Gitter channel and message me there.

**Pull request closed without merging**
