### PR TITLE
Disallows calculator returning functions (#174)

### PR DESCRIPTION
**Pull request by justinpchang**

### CODE REVIEW

**Comment by justinpchang** [comment]
Fixes issue #174

**Comment by vutran** [comment]
Let's throw the exception earlier right after the eval call.

**Comment by justinpchang** [comment]
Additionally, I don't know where else to ask this, but what are the steps of submitting a plugin to dpm?

**Comment by vutran** [comment]
> Additionally, I don't know where else to ask this, but what are the steps of submitting a plugin to dpm?

Just update the `README.md` in this file with your new Dext plugin, that's it. :)

**Pull request merged**
