### PR TITLE
RFC docs(README): add notice on the status quo

### PR DESCRIPTION
**Pull request by adnasa**
### Request for comments

At the moment, I figure that it is best to make clear the state of the union of dext.
I wanted to make clear that any new feature is not to be expected any time soon, although I could use some help with the wording.

Important here to highlight;

1. we ought to clean up the code base of `dext` first
2. only after point 1 above is address, can we move on to `2.0`

### CODE REVIEW

**Review by vutran — COMMENTED** [review]
Looks straightforward.

Maybe we can link to the v0.9 release page for anyone who prefers the current version.

**Review by vutran — APPROVED** [review]
Aside from that small bit, I think the project board is pretty straightforward.

**Comment by adnasa** [comment]
thanks for the review :)
Are you sure there is nothing to add/change?

feel free to change :)

**Review by vutran — APPROVED** [review]
Good to merge. We can update as we need so it doesn't get blocked.

**Pull request merged**
