### PR TITLE
refactor(app/renderer/components): move tests into dedicated folder with component

### PR DESCRIPTION
**Pull request by adnasa**
#### Summary 

- part of #189 
- the components are named now using hypens (`slug`?)

I tested the UI, still fine 🤪

### CODE REVIEW

**Comment by adnasa** [comment]
while browsing through the structure of the `/app` folder, I thought that we can take it a bit further with the split and have the following

```
/dext
  /electron // electron only related code
  /frontend // react
  /theme-*
  /plugin-*
  /all-other-tools-for-dext
```

**Comment by adnasa** [comment]
Finally passed the build 😄

**Comment by vutran** [comment]
Not a big issue, but just wanted to know what's the case for using kabob-case? I figured the file name to class name would be easier for searching when performing fuzzy search.

**Comment by adnasa** [comment]
yeah sorry,
I did that way too prematurely. I wanted to suggest this later anyways (before actually doing it), but then this occupational hazard got to me.

essentially, what is a great about kabob-case, is that it serves a cross-cutting concerns.
To me, in the end, it doesn't matter if a file contains a class, function, a react component or just another css file. it is a file. And naming these consistently eliminates the conginitve load when browsing through a project.

With that in mind, it actually _eases_ fuzzy searching in the editor, whatever editor you are using (or grep for that matter).

example where inconsistent naming convention of files are awkward:

```js
import React from 'react'
import { Router, Route } from 'react-router-dom'
import Icon from './Icon' 🧐
// why not just
// import Icon from './icon'
```

---

good stuff with kabob case, is that it really paves way to flat folder structure (something that I'm a big fan of.

```
theme-1
theme-2
theme-3
theme-4
  // no hidden subfolder here...
```

over 

```
/theme
  /1
  /2
  /3
  /4
```

with a flat structure like this, it gives a "parent folder" a whole new meaning too, where sub-communicates (if you will) that a group of files within a folder are tightly coupled.

---

anyway, I don't have a strong do-or-die opinion about this.  if you want to go back to the old ways, I'm flexible.

**Comment by vutran** [comment]
Awesome. That's reasonable. Let's go with that. Down case all the filenames!!

**Review by vutran — APPROVED** [review]

**Comment by adnasa** [comment]
glad to hear you like it dude. 💟 
let's do this

**Pull request merged**
