### PR TITLE
correct eslint errors

### PR DESCRIPTION
**Pull request by vutran**
Addresses #58

### CODE REVIEW

**Comment by adnasa** [comment]
After pulling this locally and run `npm i`, I got even more errors which is confusing..

**Comment by vutran** [comment]
@adnasa What errors are you receiving? Do you have any local changes that may affect it?

**Comment by adnasa** [comment]
I got the following after running a __clean__ install
https://gist.github.com/adnasa/0656a63101133d2e50a6075637e73ac4

**Comment by vutran** [comment]
Got to rebase due to changes

**Comment by adnasa** [comment]
everything is perfect now (still not being able to sleep)

**Pull request merged**
