### PR TITLE
round down values in winPosition array

### PR DESCRIPTION
**Pull request by pacharanero**
round down values in winPosition array so that they can work as integers for window position
see https://github.com/vutran/dext/issues/119#issuecomment-263587341

This works on Linux, hopefully doesn't break any of the other platforms.

### CODE REVIEW

**Comment by vutran** [comment]
Can you rebase against `develop`?

**Comment by pacharanero** [comment]
I notice you've approved the PR - do you still need a rebase against `develop`? Or can these commits from my `master` be pulled into your `develop`? I'm happy to rebase and submit a new PR if still required

**Comment by vutran** [comment]
Yes, please rebase. Want to make sure all checks passes before merging since I know `develop` has changed a bit and `master` hasn't been updated yet since the last release.

**Comment by pacharanero** [comment]
rebased off develop; have submitted a separate PR; closed this one

**Pull request closed without merging**
