### PR TITLE
chore(*): prettify and upgrade eslint

### PR DESCRIPTION
**Pull request by adnasa**
- adds `prettier`
- updates `eslint`
- uses `prop-types`

---

Now, I understand that this PR can be really noisy with 2.8K additions, but it's mostly a scroll through PR, except take note of these changes

- package.json https://github.com/DextApp/dext/pull/184/files#diff-50
- extended eslintrc https://github.com/DextApp/dext/pull/184/files#diff-1

--- 

next up (another PR)

- upgrade babel
- upgrade webpack

---

QA

check out this branch, and try out the following

- `yarn install && yarn lint && yarn build` (additional run a prod build)
 - `yarn dev`

Running the commands above, and dext is still up and running (locally at least 😉 )

### CODE REVIEW

**Comment by vutran** [comment]
I think we can just ditch eslint and let prettier handle reformatting overall. No need for linting anymore unless we want to enforce specific rulesets.

**Comment by vutran** [comment]
Aside from that LGTM.

**Review by vutran — APPROVED** [review]

**Comment by vutran** [comment]
I added the travis project since the repo was moved. Coveralls still not updating their cache to let me add from org account so it won't report correctly.

**Comment by adnasa** [comment]
aight let's do this 🚀

**Comment by adnasa** [comment]
@vutran 

btw, I forgot to reply you on this point

> I think we can just ditch eslint and let prettier handle reformatting overall. No need for linting anymore unless we want to enforce specific rulesets.

Actually, I would keep linting, since `eslint-plugin-react` offers rules that discourages usage of `this.setState` e.g in render. I wouldn't want to review code that contains this kind of mistakes :)

**Comment by vutran** [comment]
> Actually, I would keep linting, since eslint-plugin-react offers rules that discourages usage of this.setState e.g in render. I wouldn't want to review code that contains this kind of mistakes :)

Awesome! Once we move to lerna, perhaps an eslint dext plugin would be good. 😀

**Pull request merged**
